import type { Metadata } from "next";
import "../globals.css";
import Header from "../component/header";
import Footer from "../component/Footer";

import localFont from "next/font/local";

const belgiano = localFont({
  src: "./../../../public/belgiano_serif/Belgiano Serif 2.ttf",
  variable: "--font-belgiano",
  display: "swap",
});

export const metadata: Metadata = {
  title: "The Elet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${belgiano.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
